# Generated by Django 3.2.9 on 2021-12-04 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0003_alter_films_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='likeur',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
