# Generated by Django 3.2.9 on 2021-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_films_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='films',
            field=models.ManyToManyField(to='films.Films'),
        ),
    ]
